exam_app/models.py
from flask_sqlalchemy import SQLAlchemy

from exam_app import db

class Question(db.Model):
    # your model code
    id = db.Column(db.Integer, primary_key=True)
    type = db.Column(db.String(50))
    content = db.Column(db.String(500))
    answer = db.Column(db.String(200))
    options = db.Column(db.String(500))

exam_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import os
def create_app():
    # template_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'templates'))
    # app = Flask(__name__, template_folder=template_dir)
    app = Flask(__name__)

    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///exams.db'
    
    db.init_app(app)

    # No need for decorator, directly create tables here
    with app.app_context():
        db.create_all()

    # Registering the blueprints
    from .routes import main_bp
    app.register_blueprint(main_bp)

    return app

# Create the database instance without an app instance
db = SQLAlchemy()

exam_app/main.py
from . import create_app, db
from .utils import display_question


app = create_app()

app.jinja_env.globals.update(display_question=display_question)

if __name__ == '__main__':
    app.run(debug=True)

exam_app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from .models import Question
from .utils import evaluate_answer, display_question
from exam_app import db

main_bp = Blueprint('main', __name__)

"""
Flask uses a concept of blueprints for making application components and supporting common patterns within an application 
or across applications. Blueprints can greatly simplify how large applications work and provide a central means for Flask extensions 
to register operations on applications. A Blueprint object works similarly to a Flask application object,but it is not actually 
an application. Rather it is a blueprint of how to construct or extend an application.
"""

@main_bp.route('/')
def index():
    questions = Question.query.all()
    return render_template('index.html', questions=questions)

@main_bp.route('/take_exam')
def take_exam():
    questions = Question.query.all()

    # Sort/group questions by type
    tf_questions = [q for q in questions if q.type == 'tf']
    mcq_questions = [q for q in questions if q.type == 'mcq']
    matching_questions = [q for q in questions if q.type == 'matching']
    fill_in_the_blanks_questions = [q for q in questions if q.type == 'fill_in_the_blanks']

    return render_template('exam.html', 
                           tf_questions=tf_questions,
                           mcq_questions=mcq_questions,
                           matching_questions=matching_questions,
                           fill_in_the_blanks_questions=fill_in_the_blanks_questions)

# @main_bp.route('/submit_exam', methods=['POST'])
# def submit_exam():
#     questions = Question.query.all()
#     score = 0
#     for question in questions:
#         user_answer = request.form.get(str(question.id))
#         if evaluate_answer(user_answer, question.answer, question.type):
#             score += 1
#     return f"You scored {score} out of {len(questions)}"

@main_bp.route('/add_sample_data')
def add_sample_data():
    # Existing questions
    q1 = Question(type='mcq', content='What is the capital of France?', answer='Paris', options='London,Paris,Berlin,Madrid')
    q2 = Question(type='tf', content='The sun is a planet.', answer='False', options='')

    # Matching question
    q3_content = 'Match the following items with their categories:'
    q3_options = 'D. Chair, D. Ball; 4. Room, 5. Ground'
    q3_answer = 'D:4,E:5'
    q3 = Question(type='matching', content=q3_content, answer=q3_answer, options=q3_options)
    
    # Fill in the blanks question
    q4_content = 'The _____ is the largest planet in our solar system.'
    q4_answer = 'Jupiter'
    q4 = Question(type='fill_in_the_blanks', content=q4_content, answer=q4_answer, options='Earth,Venus,Mars,Jupiter')

    # Add to session and commit
    db.session.add_all([q1, q2, q3, q4])
    db.session.commit()
    return "Sample data added"

@main_bp.route('/submit_exam', methods=['POST'])
def submit_exam():
    questions = Question.query.all()
    score = 0
    correct_answers = []
    wrong_answers = []

    for question in questions:
        user_answer = request.form.get(str(question.id))
        if evaluate_answer(user_answer, question.answer, question.type):
            score += 1
            correct_answers.append(question)
        else:
            wrong_answers.append({
                'question': question,
                'user_answer': user_answer
            })

    return render_template('results.html', 
                           score=score, 
                           total=len(questions), 
                           correct_answers=correct_answers, 
                           wrong_answers=wrong_answers)

exam_app/templates/exam.html
<!-- ... Your HTML Header ... -->

<div class="container">
    <h1>Examination</h1>
    <p>Total questions fetched: {{ tf_questions|length + mcq_questions|length + matching_questions|length + fill_in_the_blanks_questions|length }}</p>
    <form action="{{ url_for('main.submit_exam') }}" method="post">

        <h2>Section 1: True or False</h2>
        {% for question in tf_questions %}
            <p>{{ loop.index }}. {{ question.content }}</p>
            {% for option in display_question(question) %}
                <input type="radio" name="{{ question.id }}" value="{{ option }}"> {{ option }}<br>
            {% endfor %}
            <br>
        {% endfor %}

        <h2>Section 2: Multiple Choice Questions</h2>
        {% for question in mcq_questions %}
            <p>{{ loop.index }}. {{ question.content }}</p>
            {% for option in display_question(question) %}
                <input type="radio" name="{{ question.id }}" value="{{ option }}"> {{ option }}<br>
            {% endfor %}
            <br>
        {% endfor %}

        <h2>Section 3: Match the Columns</h2>
        {% for question in matching_questions %}
            <p>{{ loop.index }}. {{ question.content }}</p>
            <table border="1">
                <tr>
                    <th>Column X</th>
                    <th>Column Y</th>
                </tr>
                {% set columns = question.options.split(';') %}
                {% set column_x = columns[0].split(',') %}
                {% set column_y = columns[1].split(',') %}
                {% set max_length = [column_x|length, column_y|length]|max %}
                {% for i in range(max_length) %}
                    <tr>
                        <td>{{ column_x[i] if i < column_x|length else '' }}</td>
                        <td>{{ column_y[i] if i < column_y|length else '' }}</td>
                    </tr>
                {% endfor %}
            </table>
            <label>Answer:</label>
            <input type="text" name="answer_{{ question.id }}" placeholder="E.g., A:1,B:2,C:3">
            <br><br>
        {% endfor %}
            

        <h2>Section 4: Fill in the Blanks</h2>
        {% for question in fill_in_the_blanks_questions %}
            <p>{{ loop.index }}. {{ question.content }}</p>
            {% for option in display_question(question) %}
                <input type="radio" name="{{ question.id }}" value="{{ option }}"> {{ option }}<br>
            {% endfor %}
            <br>
        {% endfor %}        

        <input type="submit" value="Submit">
    </form>
</div>

<!-- ... Your HTML Footer ... -->

exam_app/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Exam Dashboard</title>
</head>
<body>
    <h1>Welcome to the Examination Portal</h1>
    <p>Select an option:</p>
    <ul>
        <li><a href="{{ url_for('main.take_exam') }}">Take Exam</a></li>
        <!-- You can add more options as you develop further features -->
    </ul>
</body>
</html>

exam_app/templates/results.html
<!DOCTYPE html>
<html>
<head>
    <title>Exam Results</title>
</head>
<body>
    <h1>Exam Results</h1>
    <p>You scored {{ score }} out of {{ total }}</p>

    <h2>Correct Answers</h2>
    <ul>
    {% for question in correct_answers %}
        <li>{{ question.content }} - Correct Answer: {{ question.answer }}</li>
    {% endfor %}
    </ul>

    <h2>Wrong Answers</h2>
    <ul>
    {% for item in wrong_answers %}
        <li>{{ item.question.content }} - Your Answer: {{ item.user_answer }} | Correct Answer: {{ item.question.answer }}</li>
    {% endfor %}
    </ul>

</body>
</html>